language: node_js
node_js:
- '9'
- '10'
script:
- npm run lint
deploy:
  provider: npm
  email: admin@appbooster.ru
  api_key:
    secure: UCdqLp603It4gwmm2D35z6+DWmB4wVLr6mxYl5RYryIRqzOCH1kEzONUYIdSuiAba5lQFz2VvZk2WFulMoMzUWUpgrnCsC+1cJtZFDxtfIp++b3eHeoXPCMMp3jvMBwY/rOoaZQAYv2s44T7dJHlsVO5kD17zwtIXGdqKaVDTTopvmSpfBqpvogMcDgKwVVLfhYYmCveOeJ3i8a5yO4bvLF8ged664/a17QDRxu5LFm+1w5Lw3l418mvp+QiIlavd0VXngiASqQOJrLC1nnQqqM/8lK8HPIRo9cX5G2pRIHpmMZ9Qq+/icTCNKjIJ4ph71iTKIfPXv5kDbhlrYnxTzuq1EhHDVUgNFuDfsTWmk2oVKCU3KbX8J2CSmndooG5Xfu5V+hWCjCGSD1a3JplkdxYQOhQ0AdN296dPCuu7lRI5HGDnTH/cmPsUXjmt4442WZVzUo7BCM50kECdLWpb1EnpY7Vun5Ewfux0bvkhHftOq2BDNm2X5HdUorUCmbLueA5OaDZWhanFQ0WPtiKelGjZFYy6WOvHWDSsITk+zv2GwzneH5qTVROsB+k4ly1wLNZhwd+l1PO59jvb6hjNzr8YIzYnVKbTNoCTpxBu/jB0cibs5R8/2277cfzibHnzok9u8zoA8Dtpq3Fb/PEcVfJKcpoeyZprtlYT5tUBUM=
  on:
    tags: true
